### ISSUE TITLE
Once you've used a gesture, Application.Quit() crashes unity.

### ISSUE THREAD

**Issue by oafkad** [TouchScript/TouchScript#200] opened 2016-01-07 20:26 UTC
Even if I create a simple scene that just has a single sprite object.

I create the sprite.
Add Transform Gesture.
Transformer Gesture.
Release Gesture.

On Release I tell it to run Application.Quit(). Crash to desktop.

This doesn't appear to be the case when I build to my Windows 10 machine. But on my touch table it's happening every time. Across all projects. If you close out before any TS gesture is sent everything closes gracefully.

Any ideas?

[output_log.txt](https://github.com/TouchScript/TouchScript/files/81701/output_log.txt)
[2016-01-07_212300.zip](https://github.com/TouchScript/TouchScript/files/81702/2016-01-07_212300.zip)

Also: Here is the >entire< body of scripts in the scene:

``` C#
using UnityEngine;
using System.Collections;
using TouchScript.Gestures;

public class DestroyMe : MonoBehaviour {

    void OnEnable()
    {
        if (GetComponent<ReleaseGesture>())
        {
            GetComponent<ReleaseGesture>().Released += DestroyMe_Released;
        }
    }

    void OnDisable()
    {
        if (GetComponent<ReleaseGesture>())
        {
            GetComponent<ReleaseGesture>().Released -= DestroyMe_Released;
        }
    }

    private void DestroyMe_Released(object sender, System.EventArgs e)
    {
        Application.Quit();
    }
}

```

That's it. You can switch the gesture to any other gesture and the outcome should be the same :).

**Comment by oafkad** [comment] 2016-01-07 22:11
Additional observation. If you release both fingers (from resizing via transformer) simultaneously, there will be no crash. If you release one, then the other, there will be a crash.

**Comment by valyard** [comment] 2016-01-09 09:13
What OS does the touch table use?
The log says
> [TouchScript] Initialized Windows 7 touch input.

**Comment by valyard** [comment] 2016-01-09 11:18
It seems that I forgot to merge a fix for this to 7.0 branch.
Can you try your project with the latest https://github.com/TouchScript/TouchScript/tree/develop branch?

**Comment by oafkad** [comment] 2016-01-09 21:35
Alright. I won't be near the table until Monday but I'll give that a shot. It's windows 7 embedded for what it's worth.

**Comment by oafkad** [comment] 2016-01-12 20:03
Update on this issue.
5.3.0 crashes still.
BUT
5.3.1p1 does not!

So for my purposes the problem is fixed. As it works with the latest unity (on Windows 7 and 10).

**Comment by valyard** [comment] 2016-01-18 04:38
For me 5.3.1x crashes if I build a 32bit app. Are you building a 32bit app? 64bit don't crash on 5.2.2 nor on 5.3.1x.

**Comment by oafkad** [comment] 2016-01-19 19:16
Yeah building in 32, which I didn't actually notice until you mentioned it. Unfortunately I can't really downgrade at work to test it in 64 bit. But regardless, with the latest unity (the p build) it doesn't crash in 32 either.

**Comment by valyard** [comment] 2016-01-19 21:32
Hm. It does crash for me in 32bit.

**Comment by oafkad** [comment] 2016-01-19 21:38
Very peculiar. Yeah, I've double checked. My output is x86 (not the x86_64). So unless the engine is overwriting it somewhere else during build that I'm unaware it should be 32 bit.

**Comment by madhuatlink** [comment] 2016-01-20 11:46
We had a similar issue after upgrading to Unity 5. Application.Quit() crashed on the Touch screen. I don't think it has anything to do with Touchscript.

http://stackoverflow.com/questions/34068406/unity-5-2-1-build-crash-on-application-quit-with-windows-touch

**Comment by oafkad** [comment] 2016-01-20 19:20
@madhuatlink Upon removing TS from all 5 of our projects the crash stopped happening. It's entirely possible that it wasn't TS but:

A) Removing it fixed the crash.
B) The changes made above stopped it even with TS for us.

Again though, I'm open to it being entirely coincidence. Correlation != Causation, but it's a fairly consistent outcome in my neck of the woods at least. That isn't to say folks shouldn't look elsewhere though.

**Comment by valyard** [comment] 2016-01-20 19:22
I have an empty project with nothing but TouchScript crashing on me.
But I'm fairly certain that it's not TouchScript q: I blame Windows!

**Comment by oafkad** [comment] 2016-01-20 19:29
@valyard What OS are you running on? Because since I got your changes I can't replicate my crashes anymore at work or at home.

I'm using the latest 10 in both places (well more updated at home because work requires an IT for updates). 

I even updated my package at home with your latest on the front page (that has the 199 and 200 changes) and still my personal project is completely rock solid *up from crashing almost 100% of the time on editor close*.

**Comment by valyard** [comment] 2016-03-05 20:23
I'm investigating this and figured out that there are two types of crashes:
1. App has stopped working dialog.
2. Crash folder appears near the exe file.

(2) is less intrusive and lets the app to be restarted, (1) shows crash in the face.
What crash types are you guys getting?

**Comment by valyard** [comment] 2016-03-08 00:04
Can you guys test this package?
Moved some of the touch handling routines to a c++ plugin.
https://www.dropbox.com/s/z79svc15916en9e/touchscript.windows.zip?dl=0

**Comment by RicardoGuzmanVelasco** [comment] 2016-03-10 12:22
I'll try when I can!

**Comment by valyard** [comment] 2016-04-13 13:49
Has anyone tried this yet?

**Comment by musiko** [comment] 2016-05-20 02:28
I tried yesterday, with this package the application was halted by DllNotFoundException  #216

**Comment by sergipanadero** [comment] 2016-05-30 06:45
Any idea for solve the crash?
I have test on unity 5.2.3f1 and 5.3.4 and on 32 and 64 bits stills crashing.

Please i need a solution!

Thanks

**Comment by valyard** [comment] 2016-06-14 19:45
I'm not able to reproduce it o.O
Do you guys still get DLL not fount exception?
Does *_Data/Plugins folder contain WindowsTouch.dll?

**Comment by musiko** [comment] 2016-06-20 07:31
*_Data/Plugins folder does not contain WindowsTouch.dll

**Comment by valyard** [comment] 2016-06-20 21:09
Wait, how is this possible? Are you publishing for Windows?
The dll should be in the project in Plugins folder, both: 32bit and 64bit.

**Comment by valyard** [comment] 2016-06-21 10:09
Can you upload the test project?
What OS are you using?

**Comment by jonkeee** [comment] 2016-07-27 15:06
Same Problem here!
WIN7 Unity3D 5.3.4 TouchScript 8.1 (no TouchScreen connected)
If there is any TouchScript active in Scene, after Quiting the Player I get a Error Message.
With 32bit i get a CrashFolder
With 64bit I get no Crash Folder

See Testproject and Player under build/
Example Cube was the testscene
https://www.dropbox.com/s/ov2sfh8j0rpvb5w/New%20Unity%20Project.zip?dl=0

Any Ideas?

**Comment by valyard** [comment] 2016-07-28 07:46
@jonkeee can you try this build?
https://www.dropbox.com/s/z79svc15916en9e/touchscript.windows.zip?dl=0

**Comment by jonkeee** [comment] 2016-07-28 09:07
Thx for the reply!
Now the APP is not crashing anymore after shutdown.
But now the Touchscript is not working in Player. (32bit and 64bit)
No Interaction and no TouchVisuals visible.
But Touch is working in Editor..

see ouput.log
DllNotFoundException: D:/01-Projekte/New Unity Project/build/test3_Data/Plugins/WindowsTouch.dll
  at (wrapper managed-to-native) TouchScript.InputSources.InputHandlers.WindowsTouchHandler:SetScreenParams (int,int,single,single,single,single)
  at TouchScript.InputSources.InputHandlers.WindowsTouchHandler.initScaling () [0x00000] in <filename unknown>:0 
  at TouchScript.InputSources.InputHandlers.WindowsTouchHandler..ctor (TouchScript.Tags tags, System.Func`4 beginTouch, System.Action`2 moveTouch, System.Action`1 endTouch, System.Action`1 cancelTouch) [0x00000] in <filename unknown>:0 
  at TouchScript.InputSources.InputHandlers.Windows7TouchHandler..ctor (TouchScript.Tags tags, System.Func`4 beginTouch, System.Action`2 moveTouch, System.Action`1 endTouch, System.Action`1 cancelTouch) [0x00000] in <filename unknown>:0 
  at TouchScript.InputSources.StandardInput.enableWindows7Touch () [0x00000] in <filename unknown>:0 
  at TouchScript.InputSources.StandardInput.OnEnable () [0x00000] in <filename unknown>:0

**Comment by valyard** [comment] 2016-07-28 09:59
@jonkeee: I don't know why WindowsTouch.dll is not being copied. Can you see if you have it in the project and copy it to build/test3_Data/Plugins/?

**Comment by jonkeee** [comment] 2016-07-28 12:55
The Dll exists under this folder. 
I tried to copy it to the Folder Managed/ but still same error?!

**Comment by valyard** [comment] 2016-08-06 04:17
I just built your test project with the test TouchScript package in Win10 working under Parallels on OSX. The dll is being copied fine. Can you provide more details?
![2016-08-06_07-15-22](https://cloud.githubusercontent.com/assets/210516/17454630/cca6e05e-5ba5-11e6-9a66-550387351a20.png)

**Comment by jonkeee** [comment] 2016-08-09 06:43
The Dll is copied fine in WIN7 to. Also touch is working. But if i Close the Application, i get the error. "Player is not working anymore"

**Comment by valyard** [comment] 2016-08-09 07:39
Seems to be Windows 7 issue.
Report from other users:
> The touchscreen does not work for me with Windows 7 Unity 5.4 (latest release) and an IIyama T2735MSC screen. Your previous versions worked just fine. The boxes won't move or receive any touch. The old version sometimes crashes, and sometimes not. Haven't really figured out a correlation yet.

Although nmax from the forum (http://touchprefab.com/viewtopic.php?f=1&t=24473) reports that it works fine on Windows 7 with 5.3.4.

This is damn inconsistent and I don't have any touch device on win7... Need a dev with Win7 and a touch screen capable of debugging stuff.

**Comment by jonkeee** [comment] 2016-08-09 09:13
With this testproject I get no Touches in Player. 
Also no crash at App Quit.

WIN7 
Unity 5.3.4
No Touchdevice connected

Still this error in log:
Fallback handler could not load library C:/Users/Tim/Downloads/p/build/test_Data/Mono/libC:/Users/Tim/Downloads/p/build/test_Data/Plugins/WindowsTouch.dll
DllNotFoundException: C:/Users/Tim/Downloads/p/build/test_Data/Plugins/WindowsTouch.dll
  at (wrapper managed-to-native) TouchScript.InputSources.InputHandlers.WindowsTouchHandler:SetScreenParams (int,int,single,single,single,single)
  at TouchScript.InputSources.InputHandlers.WindowsTouchHandler.initScaling () [0x00000] in <filename unknown>:0 
  at TouchScript.InputSources.InputHandlers.WindowsTouchHandler..ctor (TouchScript.Tags tags, System.Func`4 beginTouch, System.Action`2 moveTouch, System.Action`1 endTouch, System.Action`1 cancelTouch) [0x00000] in <filename unknown>:0 
  at TouchScript.InputSources.InputHandlers.Windows7TouchHandler..ctor (TouchScript.Tags tags, System.Func`4 beginTouch, System.Action`2 moveTouch, System.Action`1 endTouch, System.Action`1 cancelTouch) [0x00000] in <filename unknown>:0 
  at TouchScript.InputSources.StandardInput.enableWindows7Touch () [0x00000] in <filename unknown>:0 
  at TouchScript.InputSources.StandardInput.OnEnable () [0x00000] in <filename unknown>:0

**Comment by dandushka** [comment] 2016-08-11 18:42
Could it be the wrong WindowsTouch.dll file is being grabbed in the build? 

Looks like the WindowsTouch.dll that's getting copied over is 12kb rather than the 15kb one in the x64 folder.

**Comment by jonkeee** [comment] 2016-08-16 14:52
Even with new version 8.2 the app crashes after quit.
Do i have to switch to WIN10 to fix the problem?

**Comment by valyard** [comment] 2016-08-18 07:15
8.2 doesn't include this change since it's not working for everyone...

**Comment by jonkeee** [comment] 2016-08-18 07:32
Ok so I tried it on 3 different Machines.
2x PCs WIN7 5.3.4 & 5.4 and 1PC WIN10 5.3.4 & 5.4
Game works as expected but crashes after Quit with an Access Violation Error on all machines ... also the example Projects. Don't know what's wrong with my machines :-(

For this Project I have to skip Touchscript unfortunatly. Hopefully it works for my next Project.

**Comment by Wim-Alligence** [comment] 2016-11-09 16:20
Any progress on this error?

**Comment by valyard** [comment] 2016-11-10 04:51
You don't need StandardInput if you only use TUIO.
But disabling StandardInput indeed should properly unsubscribe from Windows Touch handling hooks.
I merged native handling for Windows Touch in develop recently. In my tests I don't see ay crashes: https://github.com/TouchScript/TouchScript/releases/tag/9.0alpha1

**Comment by valyard** [comment] 2016-12-08 21:59
I was pointed out that the resulting DLLs depended on VC++ redistributable.
I resolved this dependency and published a new build: https://github.com/TouchScript/TouchScript/releases/tag/9.0alpha2
I would really appreciate if you guys tried running it.

**Closed** 2017-01-27 02:42 UTC
